# Generated by Django 5.2.5 on 2025-08-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_animal', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Conejo', 'Conejo'), ('Otro', 'Otro')], max_length=10)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField(help_text='Edad en años')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('castrado', models.BooleanField(default=False)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('vacunas', models.JSONField(blank=True, default=list)),
                ('compatibilidad_otros_animales', models.BooleanField(default=True)),
                ('compatibilidad_ninos', models.BooleanField(default=True)),
                ('comportamiento', models.TextField(blank=True, null=True)),
                ('hogar_actual', models.CharField(max_length=100)),
                ('condiciones_adopcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes_animales/')),
                ('historia', models.TextField(blank=True, null=True)),
                ('recomendaciones_cuidado', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
