# Generated by Django 5.2.5 on 2025-08-19 00:25

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_animal', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Conejo', 'Conejo'), ('Otro', 'Otro')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('edad', models.PositiveIntegerField(help_text='Edad en años')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('castrado', models.BooleanField(default=False)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('vacunas', models.JSONField(blank=True, default=list)),
                ('compatibilidad_otros_animales', models.BooleanField(default=True)),
                ('compatibilidad_ninos', models.BooleanField(default=True)),
                ('comportamiento', models.TextField(blank=True, null=True)),
                ('hogar_actual', models.CharField(max_length=100)),
                ('condiciones_adopcion', models.TextField()),
                ('historia', models.TextField(blank=True, null=True)),
                ('recomendaciones_cuidado', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='adopcionesapp.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(default='', max_length=100)),
                ('mensaje', models.TextField(max_length=1000)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcionesapp.publicacion')),
            ],
        ),
    ]
