# Generated by Django 5.2.5 on 2025-08-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcionesapp', '0002_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='asunto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.TextField(max_length=1000),
        ),
    ]
